name: panda_repartidor
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  flutter_svg: ^2.0.16
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  local_auth: ^2.1.8
  device_info_plus: ^9.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  location: ^7.0.1
  flutter_animate: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

