// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvFt35l_x2w_52d_aewO0ldDIZfxf284Q',
    appId: '1:706710228171:web:708831cf1b417d3969df4e',
    messagingSenderId: '706710228171',
    projectId: 'panda-delivery-e4e74',
    authDomain: 'panda-delivery-e4e74.firebaseapp.com',
    storageBucket: 'panda-delivery-e4e74.firebasestorage.app',
    measurementId: 'G-JN55YZ3X7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsz2XGOW6gB8egc7aNhdVyE_203a3r9Q',
    appId: '1:706710228171:android:5a463405dc711f4a69df4e',
    messagingSenderId: '706710228171',
    projectId: 'panda-delivery-e4e74',
    storageBucket: 'panda-delivery-e4e74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXgnRqgSg_xsURKPVzD-P4QvRyexUWo0',
    appId: '1:706710228171:ios:e5e66c0b0243f98769df4e',
    messagingSenderId: '706710228171',
    projectId: 'panda-delivery-e4e74',
    storageBucket: 'panda-delivery-e4e74.firebasestorage.app',
    iosBundleId: 'com.example.pandaRepartidor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtXgnRqgSg_xsURKPVzD-P4QvRyexUWo0',
    appId: '1:706710228171:ios:e5e66c0b0243f98769df4e',
    messagingSenderId: '706710228171',
    projectId: 'panda-delivery-e4e74',
    storageBucket: 'panda-delivery-e4e74.firebasestorage.app',
    iosBundleId: 'com.example.pandaRepartidor',
  );
}
